---
markdown: kramdown
highlighter: rouge
title: Akash Palrecha
tagline: AI
description: AI Lead • Pixxel
url: https://akashpalrecha.github.io/
baseurl: ''
author:
  name: Akash Palrecha
  url: https://twitter.com/akashpalrecha98
paginate: 5
exclude:
- vendor
- README.md
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
# remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
